const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const logger = require('../config/logger');

function generateEvidencePack(invoice, user, logs) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                margin: 50,
                size: 'A4',
                bufferPages: true
            });
            const buffers = [];

            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => {
                const pdfData = Buffer.concat(buffers);
                resolve(pdfData);
            });

            const leftMargin = 70;
            const pageWidth = 495;

            // --- Header ---
            doc.fontSize(24).font('Helvetica-Bold').text('EVIDENCE PACK', leftMargin, 80, { width: pageWidth, align: 'center' });
            doc.moveDown(0.3);
            doc.fontSize(10).font('Helvetica').fillColor('#666666')
                .text('Generated by NudgePay Legal Tools', leftMargin, doc.y, { width: pageWidth, align: 'center' });
            doc.fillColor('#000000');
            doc.moveDown(1.5);

            // --- Legal Disclaimer Box ---
            const disclaimerY = doc.y;
            doc.rect(50, disclaimerY, 495, 50).fillAndStroke('#FEE2E2', '#DC2626');
            doc.fontSize(8).fillColor('#991B1B').font('Helvetica-Bold')
                .text('LEGAL DISCLAIMER', 60, disclaimerY + 10, { width: 475 });
            doc.fontSize(7).font('Helvetica').fillColor('#7F1D1D')
                .text('This document is a compilation of records for evidence purposes only. NudgePay is not a law firm and this does not constitute legal advice or certification.',
                    60, disclaimerY + 22, { width: 475, align: 'left' });
            doc.fillColor('#000000');
            doc.y = disclaimerY + 60;
            doc.moveDown(1);

            // --- Section 1: Debt Overview ---
            doc.fontSize(16).font('Helvetica-Bold').text('1. DEBT OVERVIEW', leftMargin, doc.y);
            doc.moveDown(1);

            // Draw table rows
            const tableTop = doc.y;
            const labelX = leftMargin;
            const valueX = leftMargin + 150;
            const rowHeight = 22;
            let currentY = tableTop;

            const addRow = (label, value, isRed = false) => {
                doc.fontSize(10).font('Helvetica-Bold').fillColor('#374151').text(label, labelX, currentY);
                doc.fontSize(10).font('Helvetica').fillColor(isRed ? '#DC2626' : '#000000').text(value, valueX, currentY, { width: 300 });
                currentY += rowHeight;
            };

            // Calculate days overdue properly
            const dueDate = new Date(invoice.due_date);
            const today = new Date();
            const diffTime = today - dueDate;
            const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));

            let daysOverdueText;
            let isOverdue = false;

            if (invoice.status === 'paid') {
                daysOverdueText = 'PAID';
            } else if (diffDays < 0) {
                daysOverdueText = `Due in ${Math.abs(diffDays)} days`;
            } else if (diffDays === 0) {
                daysOverdueText = 'Due Today';
                isOverdue = true;
            } else {
                daysOverdueText = `${diffDays} Days Overdue`;
                isOverdue = true;
            }

            addRow('Creditor:', user.name || 'N/A');
            addRow('Debtor:', invoice.client_name);
            addRow('Debtor Email:', invoice.client_email);
            addRow('Invoice Number:', invoice.invoice_number);
            addRow('Total Amount:', `${invoice.currency} ${invoice.amount}`);
            addRow('Due Date:', invoice.due_date);
            addRow('Status:', daysOverdueText, isOverdue);

            if (invoice.status === 'paid' && invoice.paid_at) {
                addRow('Paid On:', new Date(invoice.paid_at).toLocaleDateString());
            }

            doc.y = currentY + 10;
            doc.moveDown(1);

            // --- Section 2: Communication Log ---
            doc.fontSize(16).font('Helvetica-Bold').fillColor('#000000').text('2. COMMUNICATION LOG', leftMargin, doc.y);
            doc.moveDown(0.5);
            doc.fontSize(10).font('Helvetica-Oblique').fillColor('#6B7280')
                .text('The following attempts were made to collect payment:', leftMargin, doc.y, { width: pageWidth });
            doc.fillColor('#000000');
            doc.moveDown(1);

            // Table header
            const logTableTop = doc.y;
            const dateX = leftMargin;
            const typeX = leftMargin + 80;
            const subjectX = leftMargin + 180;
            const statusX = leftMargin + 380;

            // Header background
            doc.rect(50, logTableTop, 495, 25).fillAndStroke('#F3F4F6', '#D1D5DB');

            doc.fontSize(9).font('Helvetica-Bold').fillColor('#374151');
            doc.text('Date', dateX, logTableTop + 8, { width: 70 });
            doc.text('Type', typeX, logTableTop + 8, { width: 90 });
            doc.text('Subject', subjectX, logTableTop + 8, { width: 190 });
            doc.text('Status', statusX, logTableTop + 8, { width: 60 });

            doc.fillColor('#000000');
            let logY = logTableTop + 35;

            // Log entries
            if (logs && logs.length > 0) {
                doc.fontSize(9).font('Helvetica');
                logs.forEach((log, index) => {
                    const bgColor = index % 2 === 0 ? '#FFFFFF' : '#F9FAFB';
                    doc.rect(50, logY - 5, 495, 22).fillAndStroke(bgColor, '#E5E7EB');

                    doc.fillColor('#000000');
                    doc.text(new Date(log.date).toLocaleDateString(), dateX, logY, { width: 70 });
                    doc.text(log.type.toUpperCase().replace('_', ' '), typeX, logY, { width: 90 });
                    doc.text(log.subject.substring(0, 30) + '...', subjectX, logY, { width: 190 });
                    doc.fillColor('#059669').text('SENT', statusX, logY, { width: 60 });
                    doc.fillColor('#000000');

                    logY += 22;
                });
            } else {
                doc.fontSize(9).font('Helvetica-Oblique').fillColor('#9CA3AF')
                    .text('No automated emails recorded.', dateX, logY, { width: pageWidth });
                logY += 22;
            }

            doc.y = logY + 20;
            doc.moveDown(1);

            // --- Section 3: Declaration ---
            doc.fontSize(16).font('Helvetica-Bold').fillColor('#000000').text('3. CREDITOR DECLARATION', leftMargin, doc.y);
            doc.moveDown(1);

            let declarationText;
            if (invoice.status === 'paid') {
                declarationText = `I, ${user.name || 'the undersigned'}, declare that the above information is true and correct to the best of my knowledge. This invoice was paid on ${invoice.paid_at ? new Date(invoice.paid_at).toLocaleDateString() : 'the recorded date'}.`;
            } else {
                declarationText = `I, ${user.name || 'the undersigned'}, declare that the above information is true and correct to the best of my knowledge. The debt remains unpaid as of ${new Date().toLocaleDateString()}.`;
            }

            doc.fontSize(10).font('Helvetica').fillColor('#000000')
                .text(declarationText, leftMargin, doc.y, { width: 450, align: 'left', lineGap: 3 });

            doc.moveDown(2);
            doc.fontSize(10).font('Helvetica').text(`Date: ${new Date().toLocaleDateString()}`, leftMargin, doc.y);
            doc.moveDown(2);

            // Signature line
            const signatureY = doc.y;
            doc.moveTo(380, signatureY).lineTo(520, signatureY).stroke();
            doc.fontSize(9).fillColor('#6B7280').text('Signature', 430, signatureY + 5);

            // Footer
            doc.fontSize(7).fillColor('#9CA3AF')
                .text(`Generated on ${new Date().toLocaleString()} | NudgePay Evidence Pack`,
                    50, 750, { width: 495, align: 'center' });

            doc.end();

        } catch (error) {
            reject(error);
        }
    });
}

module.exports = { generateEvidencePack };
